# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]=#120d0f

# Main text color
theme[main_fg]=#f4e0e7

# Title color for boxes
theme[title]=#f4e0e7

# Highlight color for keyboard shortcuts
theme[hi_fg]=#eeb7d0

# Background color of selected item in processes box
theme[selected_bg]=#20171b

# Foreground color of selected item in processes box
theme[selected_fg]=#eeb7d0

# Color of inactive/disabled text
theme[inactive_fg]=#817177

# Color of text appearing on top of graphs, i.e uptime and current network graph scaling
theme[graph_text]=#f8e0ff

# Background color of the percentage meters
theme[meter_bg]=#817177

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]=#f8e0ff

# CPU, Memory, Network, Proc box outline colors
theme[cpu_box]=#faa6df
theme[mem_box]=#ffd8c5
theme[net_box]=#f0abc7
theme[proc_box]=#eda5e8

# Box divider line and small boxes line color
theme[div_line]=#52444a

# Temperature graph color (Green -> Yellow -> Red)
theme[temp_start]=#ffd8c5
theme[temp_mid]=#ffedee
theme[temp_end]=#f895c4

# CPU graph colors (Teal -> Sapphire -> Lavender)
theme[cpu_start]=#dedcff
theme[cpu_mid]=#eeb3f5
theme[cpu_end]=#f9b8ec

# Mem/Disk free meter (Mauve -> Lavender -> Blue)
theme[free_start]=#faa6df
theme[free_mid]=#f9b8ec
theme[free_end]=#eda5e8

# Mem/Disk cached meter (Sapphire -> Blue -> Lavender)
theme[cached_start]=#eeb3f5
theme[cached_mid]=#eda5e8
theme[cached_end]=#f9b8ec

# Mem/Disk available meter (Peach -> Maroon -> Red)
theme[available_start]=#ffbbcd
theme[available_mid]=#f0abc7
theme[available_end]=#f895c4

# Mem/Disk used meter (Green -> Teal -> Sky)
theme[used_start]=#ffd8c5
theme[used_mid]=#dedcff
theme[used_end]=#ebd1ff

# Download graph colors (Peach -> Maroon -> Red)
theme[download_start]=#ffbbcd
theme[download_mid]=#f0abc7
theme[download_end]=#f895c4

# Upload graph colors (Green -> Teal -> Sky)
theme[upload_start]=#ffd8c5
theme[upload_mid]=#dedcff
theme[upload_end]=#ebd1ff

# Process box color gradient for threads, mem and cpu usage (Sapphire -> Lavender -> Mauve)
theme[process_start]=#eeb3f5
theme[process_mid]=#f9b8ec
theme[process_end]=#faa6df
