# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]=#0d0f0a

# Main text color
theme[main_fg]=#e3e7d8

# Title color for boxes
theme[title]=#e3e7d8

# Highlight color for keyboard shortcuts
theme[hi_fg]=#b6ce9e

# Background color of selected item in processes box
theme[selected_bg]=#171b13

# Foreground color of selected item in processes box
theme[selected_fg]=#b6ce9e

# Color of inactive/disabled text
theme[inactive_fg]=#72776b

# Color of text appearing on top of graphs, i.e uptime and current network graph scaling
theme[graph_text]=#fff7d2

# Background color of the percentage meters
theme[meter_bg]=#72776b

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]=#fff7d2

# CPU, Memory, Network, Proc box outline colors
theme[cpu_box]=#5bd0df
theme[mem_box]=#beeda0
theme[net_box]=#c6c177
theme[proc_box]=#75cf9d

# Box divider line and small boxes line color
theme[div_line]=#454a3e

# Temperature graph color (Green -> Yellow -> Red)
theme[temp_start]=#beeda0
theme[temp_mid]=#eaf6c9
theme[temp_end]=#c5b542

# CPU graph colors (Teal -> Sapphire -> Lavender)
theme[cpu_start]=#bcecb3
theme[cpu_mid]=#90d7a0
theme[cpu_end]=#89dcc6

# Mem/Disk free meter (Mauve -> Lavender -> Blue)
theme[free_start]=#5bd0df
theme[free_mid]=#89dcc6
theme[free_end]=#75cf9d

# Mem/Disk cached meter (Sapphire -> Blue -> Lavender)
theme[cached_start]=#90d7a0
theme[cached_mid]=#75cf9d
theme[cached_end]=#89dcc6

# Mem/Disk available meter (Peach -> Maroon -> Red)
theme[available_start]=#cad48d
theme[available_mid]=#c6c177
theme[available_end]=#c5b542

# Mem/Disk used meter (Green -> Teal -> Sky)
theme[used_start]=#beeda0
theme[used_mid]=#bcecb3
theme[used_end]=#aee9b2

# Download graph colors (Peach -> Maroon -> Red)
theme[download_start]=#cad48d
theme[download_mid]=#c6c177
theme[download_end]=#c5b542

# Upload graph colors (Green -> Teal -> Sky)
theme[upload_start]=#beeda0
theme[upload_mid]=#bcecb3
theme[upload_end]=#aee9b2

# Process box color gradient for threads, mem and cpu usage (Sapphire -> Lavender -> Mauve)
theme[process_start]=#90d7a0
theme[process_mid]=#89dcc6
theme[process_end]=#5bd0df
